[project]
name = "tyche-job-hunt"
version = "0.1.0"
description = "simple job hunt tracking web like setup"
readme = "README.md"
authors = [
    { name = "gabofcampos", email = "gabrielfernandezcamposllc@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "black>=26.5.1",
    "isort>=9.0.2",
    "streamlit>=1.64.0",
]

[dependency-groups]
dev = [
    "assertpy>=1.1",
    "pytest>=9.1.1",
]
